

DEFINE FILE FORMAT {{db}}.RAW.SCOPUS_JSON_FF
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = FALSE
    COMMENT = 'JSON format for Scopus API response envelopes';

DEFINE TABLE {{db}}.RAW.RAW_SCOPUS (
    RAW VARIANT NOT NULL,
    FILENAME VARCHAR NOT NULL,
    FILE_ROW_NUMBER INTEGER NOT NULL,
    LOADED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;
